// Blockliste: Ads-Library-Link / Fanpage-Link / ID / Name eintragen, Tabelle mit Links, Filter im Scrape
const { playwright, login, ok, BASE_URL } = require('./helpers');
const { chromium } = playwright();
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1400, height: 900 } });
  await login(page);
  await page.goto(`${BASE_URL}/settings?tab=blocklist`, { waitUntil: 'networkidle' });
  await page.evaluate(() => localStorage.removeItem('blocklist'));
  await page.reload({ waitUntil: 'networkidle' });
  const input = page.locator('[data-testid="block-input"]');
  await input.fill('https://www.facebook.com/ads/library/?active_status=all&ad_type=all&country=DE&view_all_page_id=123456789&search_type=page');
  ok((await page.locator('[data-testid="block-preview"]').innerText()).includes('Page-ID 123456789'), 'Vorschau erkennt die Page-ID aus dem Ads-Library-Link');
  await page.keyboard.press('Enter');
  await page.waitForSelector('[data-testid="block-table"]');
  await input.fill('facebook.com/987654321');
  await page.click('[data-testid="block-add"]');
  await input.fill('Spam Seite');
  ok((await page.locator('[data-testid="block-preview"]').innerText()).includes('nur den Seitennamen'), 'Vorschau warnt bei reinem Namen');
  await page.keyboard.press('Enter');
  await page.waitForFunction(() => document.querySelectorAll('[data-testid="block-row"]').length === 3);
  const rows = page.locator('[data-testid="block-row"]');
  const r0 = rows.nth(0);
  ok((await r0.locator('a[href="https://www.facebook.com/123456789"]').count()) === 1, 'Spalte Fanpage: Link zur Seite');
  const ads = await r0.locator('a:has-text("Anzeigen")').getAttribute('href');
  ok(ads.includes('ads/library') && ads.includes('view_all_page_id=123456789'), 'Spalte Ads Library: Link auf die Anzeigen dieser Seite');
  ok((await rows.nth(2).innerText()).includes('nur Name'), 'Namens-Eintrag ohne ID gekennzeichnet');
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('blocklist')));
  ok(stored.length === 3 && stored[0].pageId === '123456789' && stored[1].pageId === '987654321' && !stored[2].pageId, 'Blockliste gespeichert (IDs erkannt)');
  await input.fill('123456789');
  ok(await page.locator('[data-testid="block-add"]').isEnabled(), 'ID-Eingabe möglich');
  await page.click('[data-testid="block-add"]');
  await page.waitForTimeout(150);
  ok((await rows.count()) === 3, 'gleiche ID nicht doppelt');
  await rows.nth(1).locator('button[title="Von Blockliste entfernen"]').click();
  await page.waitForFunction(() => document.querySelectorAll('[data-testid="block-row"]').length === 2);
  ok(true, 'Eintrag entfernt');
  await browser.close();
})().catch(e => { console.error('FAIL:', e.message); process.exit(1); });
